### ISSUE TITLE
Plugin is not working in IntelliJ IDEA 2023.3.1 and later vesion when running any program

### ISSUE THREAD

**Issue by nsv671** [actual-kwarter/YoshisIslandProgressBar#3]
![image](https://github.com/actual-kwarter/YoshisIslandProgressBar/assets/70027984/4e976679-7dba-4c4f-bef8-70ca76040d83)

![image](https://github.com/actual-kwarter/YoshisIslandProgressBar/assets/70027984/303ba5ee-b160-45b6-ae0b-1877726a60b2)

![image](https://github.com/actual-kwarter/YoshisIslandProgressBar/assets/70027984/74ebc9c0-ac02-4e0a-9e64-cd84530aecba)

**Comment by actual-kwarter** [comment]
@nsv671 Can you provide more details? Have you restarted since installing the plugin?

I'm running IntelliJ IDEA 2023.3.4 (Ultimate Edition) and it's working with no issues.

**Comment by nsv671** [comment]
Hi @actual-kwarter I'm also running IntelliJ IDEA 2023.3.4 (Community Edition) and it's working with no issues. in IntelliJ IDEA 2023.3.2 (Community Edition) i was facing this issue.

![image](https://github.com/actual-kwarter/YoshisIslandProgressBar/assets/70027984/d868a4bc-8010-4068-a278-b9d8330b4e7b)
